### ISSUE TITLE
Not returning data struct when custom import populates the fields.

### ISSUE THREAD

**Issue by TcM1911** [traefik/yaegi#1132]
There are too many moving parts to produce a simple POC.

A custom import has a function that say returns data from a database:
```go
func (h Handler) ReturnData(value interface) {
     // Returns and populates the struct
}
```

This function is called from a script and the result is added to a slice.
```go
result := make([]interface{}, 0)
...
t := *T
handler.ReturnData(t)
result = append(result, t)
...

return result
```

The script is executed as a "plugin". The data in the array is not returned. It appears as it's getting collected by the GC. You can access the data inside the script fine, you just can't return it.

If the script makes a copy of the data, it returns fine.

This works:
```go
result := make([]interface{}, 0)
...
t := *T
handler.ReturnData(t)
cpy := *t
result = append(result, &cpy)
...

return result
```

**Comment by mvertes** [comment]
The information provided is not sufficient for me to isolate an issue, reproduce it and fix it. I encourage you to retry with the last version of yaegi, as a lot of issues regarding interfaces have been fixed since you filed the issue. Or to go further, I really need a reproducible test case.

Thanks.
