### ISSUE TITLE
Retrieve value from valueInterface

### ISSUE THREAD

**Issue by vitrun** [traefik/yaegi#989]
#### Proposal

Retrieve value from valueinterface

#### Background
```go
type DTO = map[string]interface{}

func Invoke(ctx context.Context, req DTO) (*DTO, error) {
	return &DTO{
		"trace_id": req["trace_id"],
	}, nil
}
```
Evaluate above code and we get `interp.valueInterface` of key "trace_id", however, I found no way to retrieve the value of `interp.valueInterface` .

Can we have some function to retrieve it? It might look like: 
```go
func GetValue(vi valueInterface) reflect.Value {
    return vi.value
}
```

#### Workarounds
no

**Comment by mpl** [comment]
Hi,

You should never have to deal with an interp.valueInterface, because the API should never put you in such a situation. If it does, it means there's a bug and which should fix it so that the API directly gives you a reflect.Value.

Can you please give us the full example of how you end up in such a situation?

thanks.

**Comment by vitrun** [comment]
Hi, @mpl see [#991](https://github.com/traefik/yaegi/issues/991)
